name: shotwell
version: '0.29.3'
summary: Shotwell photo manager
description: |
  Shotwell is a digital photo organizer designed for the GNOME desktop
  environment. It allows you to import photos from disk or camera, organize
  them in various ways, view them in full-window or fullscreen mode, and
  export them to share with others. It is able to manage a lot of different
  image formats, also including raw CR2 files.
confinement: strict
grade: stable

slots:
  dbus-shotwell:
    interface: dbus
    bus: session
    name: org.gnome.Shotwell

apps:
  shotwell:
    command: desktop-launch shotwell --datadir $SNAP_USER_COMMON
    desktop: usr/share/applications/shotwell.desktop
    environment:
        CAMLIBS: $SNAP/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.9
        IOLIBS: $SNAP/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0
    plugs:
      - x11
      - unity7
      - home
      - wayland
      - network
      - mount-observe
      - gsettings
      - removable-media
      - raw-usb

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604:gnome-3-26-1604

parts:
  gnome-platform:
    plugin: nil
    after: [desktop-gnome-platform]
    override-build: |
      echo "deb http://ppa.launchpad.net/ubuntu-desktop/gnome-3-26/ubuntu xenial main" | tee /etc/apt/sources.list.d/gnome-3-26.list
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 399B698EEA9EF163B6F9A0F62CC98497A1231595
      apt update
      apt upgrade -yy
    prime: [-*]

  gexiv:
    source: https://download.gnome.org/sources/gexiv2/0.10/gexiv2-0.10.8.tar.xz
    plugin: meson
    override-build: |
      apt-get install -y python3-setuptools python3-pip
      pip3 install meson
      snapcraftctl build
    after: [exiv]
  exiv:
    source: https://github.com/Exiv2/exiv2.git
    source-commit: 7bdba2d71977cb613ad3fbbfc6c08e8df81de0b2
    plugin: cmake
    build-packages:
      - libc6
      - libexpat1
      - libgcc1
      - libstdc++6
      - zlib1g
  shotwell:
    source: https://github.com/GNOME/shotwell/archive/shotwell-0.29.3.tar.gz
    plugin: meson
    meson-parameters: [--prefix=/usr, -Dudev=false]
    build-packages:
      - desktop-file-utils
      - gnome-doc-utils
      - gobject-introspection
      - libgirepository1.0-dev
      - libgcr-3-dev
      - libgdata-dev
      - libexif-dev
      - libgee-0.8-dev
      - libgexiv2-dev
      - libglib2.0-dev
      - libgphoto2-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgtk-3-dev
      - libgudev-1.0-dev
      - libjson-glib-dev
      - libraw-dev
      - librest-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libwebkit2gtk-4.0-dev
      - libxml2
      - m4
      - valac
      - libaccounts-glib-dev
      - libsignon-glib-dev
      - libunity-dev
      - python-scour
      - intltool
      - appstream-util
      - yelp-tools
    stage-packages:
      - libc6
      - libcairo2
      - libexif12
      - libgcr-ui-3-1
      - libgdata22
      - libgdk-pixbuf2.0-0
      - libgee-0.8-2
      - libglib2.0-0
      - libgphoto2-6
      - libgphoto2-port12
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk-3-0
      - libgudev-1.0-0
      - libjson-glib-1.0-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libraw15
      - librest-0.7-0
      - libsoup2.4-1
      - libsqlite3-0
      - libunity9
      - libwebkit2gtk-4.0-37
      - libxml2
      - librsvg2-common
      - dbus-x11
      - dconf-tools
      - libdb5.3
    override-build: |
      sed -i 's|Icon=shotwell|Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/shotwell.png|g' misc/shotwell.desktop.in
      snapcraftctl build
    after: [gnome-platform, gexiv]
